//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalogos.Models.Intranet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcion
    {
        public int FuncionID { get; set; }
        public Nullable<int> FuncionPadreID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Url { get; set; }
        public int TipoFuncionID { get; set; }
        public bool Activo { get; set; }
        public string Metadata { get; set; }
        public Nullable<int> Orden { get; set; }
    }
}
