//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalogos.Models.Intranet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int UsuarioID { get; set; }
        public string Pass { get; set; }
        public string Nombre { get; set; }
        public bool Activo { get; set; }
        public Nullable<bool> Recordarme { get; set; }
        public string Foto { get; set; }
        public string NombreCompleto { get; set; }
    }
}
